### ISSUE TITLE
About the hyperparameter 

### ISSUE THREAD

**Issue by ZYFZYF** [kevaldoshi17/TiSAT#1]
There is a hyperparameter ![](https://latex.codecogs.com/svg.image?\delta_{max})   during evaluation. 
But the paper doesn't seem to mention how to set it up, and what was chosen in the experiment.
Is it possible to try to eliminate it with 
![](https://latex.codecogs.com/svg.image?NADD&space;=&space;\frac{1}{S}\sum_{i=1}^S\frac{T_i&space;-&space;\tau_i}{e_i&space;-&space;\tau_i&space;&plus;&space;1})
where ![](https://latex.codecogs.com/svg.image?e_i) is the position where anomaly ends

**Comment by kevaldoshi17** [comment]
The hyperparameter is used to select what the maximum tolerable delay should be, and that depends on the application itself. The problem with the equation that you mention is that for cases where the anomaly lasts for several thousand instances (for eg. 100k), setting the delay as 100k seconds is not really reasonable since that is equivalent to ~ 30 hours. So in our experiments, we set it as ~10% of e_i from your equation. For example, in SWAT the longest anomaly sequence is ~50k instances, so we set delta max as 5k.
